=== lhrolim/softwrench/softwrench.sW4.test/App_data/Client/test_only/Properties.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/Properties"
	xmlns:tns="http://www.example.org/Properties" elementFormDefault="qualified">

  <element name="Properties" type="tns:Property"></element>

  <complexType name="Property">
    <choice minOccurs="0" maxOccurs="unbounded">
      <element name="property" type="tns:Parameter"
        maxOccurs="unbounded" minOccurs="1">
      </element>
      <element name="environment" type="tns:Environment"
        maxOccurs="unbounded" minOccurs="0">
      </element>
    </choice>
  </complexType>

  <complexType name="Environment">
    <choice minOccurs="0" maxOccurs="unbounded">
      <element name="property" type="tns:Parameter"></element>
    </choice>
    <attribute name="key" type="string" use="required" />
  </complexType>

  <complexType name="Parameter">
    <attribute name="key" type="string" use="required"></attribute>
    <attribute name="value" type="string" use="required"></attribute>
  </complexType>
</schema>

=== lhrolim/softwrench/softWrench.sW4.Web/App_Data/client/gric/properties.xml
<?xml version="1.0" encoding="utf-8" ?>
<Properties xmlns="http://www.example.org/Properties" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://www.example.org/Properties ../../Schema/Properties.xsd ">
  
  <property key="baseWSPrefix" value="SW"/>
  <property key="externalSystemName" value="SW" />
  <property key="wsprovider" value="mif" />
  <property key="maximo_DB_provider" value="System.Data.SQL"/>
  <property key="swdb_provider" value="System.Data.SQL"/>
  <property key="defaultOrgId" value="EAGLENA"/>
  <property key="defaultSiteId" value="VQ"/>
  <property key="composition.mainbuttonstoshow" value="cancel"/>
  <property key="sourcemapping" value="maximo7.5"/>
  <property key="targetmapping" value="maximo7.5"/>
  <property key="maximoutc" value="-7"/>



  <environment key="dev">
    <property key="basewsURL" value="http://192.168.2.105:9080/meaweb/wsdl/" />
    <property key="maximo_DB_url" value="Data Source=192.168.2.105;Initial Catalog=SWMAX;User Id=MAXIMO;password=MAXIMO;" />
    <property key="swdb_url" value="Data Source=192.168.2.105;Initial Catalog=SWDB_SWMAX;User Id=sw;password=softwrench;" />
  </environment>

  <environment key="qa">
    <property key="basewsURL" value="http://192.168.2.107/meaweb/wsdl/" />
    <property key="maximo_DB_url" value="Data Source=192.168.2.21;Initial Catalog=GRC75MAX;User Id=MAXIMO;password=MAXIMO;" />
    <property key="swdb_url" value="Data Source=192.168.2.21;Initial Catalog=SWDB;User Id=sw;password=sw@dm1n;" />
    <property key="ldapServer" value="192.168.2.11"/>
    <property key="ldapPortNumber" value="389"/>
    <property key="ldapBaseDn" value="ou=GROUPS,ou=MAXIMO,dc=sas,dc=local"/>
    <property key="mifcredentials.user" value="maxadmin"/>
    <property key="mifcredentials.password" value="M@xadm1n"/>
  </environment>

  <environment key="prod">
    <property key="maximo_DB_provider" value="System.Data.SQL"/>
    <property key="defaultOrgId" value="GRGE"/>
    <property key="defaultSiteId" value=""/>
    <property key="basewsURL" value="http://10.20.24.76/meaweb/wsdl/" />
    <property key="maximo_DB_url" value="Data Source=10.20.24.75;Initial Catalog=GRC75MAX;User Id=MAXIMO;password=MAXIMO;" />
    <property key="swdb_url" value="Data Source=10.20.24.75;Initial Catalog=SW;User Id=MAXIMO;password=MAXIMO;" />
    <property key="swdb_provider" value="System.Data.SQL"/>
    <property key="ldapServer" value="10.12.4.41"/>
    <property key="ldapPortNumber" value="389"/>
    <property key="ldapBaseDn" value="DC=GRC,DC=LOCAL"/>
    <property key="mifcredentials.user" value="mxintadm"/>
    <property key="mifcredentials.password" value="M@x1mo23"/>
  </environment>
  
</Properties>

=== lhrolim/softwrench/softWrench.sW4.Web/App_Data/client/otb/properties.xml
<?xml version="1.0" encoding="utf-8" ?>
<Properties xmlns="http://www.example.org/Properties" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://www.example.org/Properties ../../Schema/Properties.xsd ">
  <property key="baseWSPrefix" value="SW"/>
  <property key="externalSystemName" value="SW" />
  <property key="wsprovider" value="mif" />
  <property key="basewsURL" value="http://192.168.2.105:9080/meaweb/wsdl/" />
  <property key="maximo_DB_url" value="Data Source=192.168.2.105;Initial Catalog=SWMAX;User Id=MAXIMO;password=MAXIMO;" />
  <property key="maximo_DB_provider" value="System.Data.SQL"/>
  <property key="swdb_provider" value="System.Data.SQL"/>
  
  <property key="defaultOrgId" value="EAGLENA"/>
  <property key="defaultSiteId" value="BEDFORD"/>
  <property key="sourcemapping" value="maximo7.5"/>
  

  <environment key="dev">
    <property key="swdb_url" value="Data Source=192.168.2.105;Initial Catalog=SWDB_SWMAX;User Id=sw;password=softwrench;" />
  </environment>

  <environment key="qa">
    <property key="swdb_url" value="Data Source=192.168.2.105;Initial Catalog=SWDB_SWMAX;User Id=sw;password=softwrench;" />
  </environment>

</Properties>

=== lhrolim/softwrench/softWrench.sW4.Web/App_Data/client/tva/properties.xml
<?xml version="1.0" encoding="utf-8" ?>
<Properties xmlns="http://www.example.org/Properties" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://www.example.org/Properties ../../Schema/Properties.xsd ">
  <property key="baseWSPrefix" value="SW"/>
  <property key="externalSystemName" value="SW" />

  <property key="basewsURL" value="http://tva75dev.cts.com:9080/meaweb/wsdl/" />
  <property key="maximo_DB_url" value="Data Source=10.50.100.51;Initial Catalog=TVA75MAX;User Id=MAXIMO;password=MAXIMO;" />
  <property key="swdb_url" value="Data Source=10.50.100.51;Initial Catalog=SWDB_TVA75MAX;User Id=sw;password=softwrench;" />
  <property key="maximo_DB_provider" value="System.Data.SQL"/>
  
  <property key="swdb_provider" value="System.Data.SQL"/>
  <property key="maxAttachmentSize" value="10"/> <!--in MB-->
  <property key="maxScreenshotSize" value="5"/> <!-- in MB-->
  <property key="allowedAttachmentExtensions" value="pdf,zip,txt,jpg,bmp,doc,docx,dwg,csv,xls,xlsx,ppt,xml,xsl,html,rtf,png"/>
  <property key="defaultOrgId" value="EAGLENA"/>
  <property key="defaultSiteId" value="BEDFORD"/>

  <property key="wsprovider" value="mif" />
  <property key="sourcemapping" value="maximo7.5"/>
  <property key="targetmapping" value="tvamaximo_target"/>
  
  <property key="email.smtp.host" value="mail.softwrenchsolutions.com"/>
  <!--property key="email.smtp.port" value="587"/-->
  <property key="email.stmp.enableSSL" value="true"/>

  <environment key="dev62">
    <property key="maximo_DB_url" value="Data Source=10.50.100.43;Initial Catalog=TVA62MAX;User Id=MAXIMO;password=Max7118;" />
    <property key="swdb_url" value="Data Source=10.50.100.43;Initial Catalog=SWDB_TVA75MAX;User Id=sw;password=softwrench;" />
    <property key="wsprovider" value="mea" />
    <property key="basewsURL" value="http://tva62dev.cts.com/meaweb/services/" />
  </environment>

  <environment key="dev75">
    <property key="maximo_DB_url" value="Data Source=10.50.100.51;Initial Catalog=TVA75MAX;User Id=MAXIMO;password=MAXIMO;" />
    <property key="swdb_url" value="Data Source=10.50.100.43;Initial Catalog=SWDB_TVA75MAX;User Id=sw;password=softwrench;" />
    <property key="wsprovider" value="mif" />
    <property key="basewsURL" value="http://tva75dev.cts.com:9080/meaweb/wsdl/" />
  </environment>


</Properties>

=== lhrolim/softwrench/softWrench.sW4.Web/App_Data/client/hapag/properties.xml
<?xml version="1.0" encoding="utf-8" ?>
<Properties xmlns="http://www.example.org/Properties" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://www.example.org/Properties ../../Schema/Properties.xsd ">

	<property key="list.click.mode" value="output"/>
	<property key="list.click.popupmode" value="browser"/>
	<property key="popup.window.titlestrategy" value="idonly"/>
	<property key="baseWSPrefix" value="MXSW4"/>
	<property key="externalSystemName" value="SW" />
	<property key="defaultOrgId" value="EAGLENA"/>
	<property key="defaultSiteId" value="BEDFORD"/>
	<property key="faqfspath" value="C:\faqAttachments\" />
	<property key="i18nrequired" value="true" />
	<property key="list.paginationsize" value="100"/>
	<property key="list.paginationoptions" value="10,30,100"/>
	<property key="list.advancedfilter.showsearchicon" value="false"/>
	<property key="successmessagetimeout" value="10000"/>

	<property key="maximo_DB_provider" value="IBM.Data.DB2" />
	<property key="maximoutc" value="-7"/>
	<property key="sourcemapping" value="maximo7.2.1"/>
	<!--  <property key="wsprovider" value="mif" />-->
	<property key="targetmapping" value="ism"/>
	<property key="multitenantprefix" value="HLC-%"/>
	<property key="globaservletpath" value="https://170.225.28.205/HAPAGLLOYDINCTestWS/DocHandlerServlet"/>
	<property key="ignorewscerterrors" value="true"/>

	<property key="faqusefullinksPath" value="C:\ServiceIT\config\SR_FAQ.txt"/>
	<property key="serviceItLoginPath" value="C:\ServiceIT\config\ServiceITLogin.properties"/>
	<property key="businessmatrixPath" value="C:\ServiceIT\config\businessmatrix"/>
	<property key="ssoServicesQueryPath" value="C:\ServiceIT\config\SSO_SERVICES_QUERY.txt"/>
	<property key="loginErrorMessage" value="Ungültiger Username oder falsches Passwort \n Invalid Username or Bad Password \n No válido Nombre de usuario o contraseña incorreta"/>
	<property key="loginUserNameMessage" value="Username is required \n Username wird benötigt \n nombre de usuario es necessario"/>
	<property key="loginPasswordMessage" value="Password is required \n Passwort wird benötigt \n se requiere contraseña"/>
	<property key="defaultChangeTeamplateId" value="HLCDECHG"/>
	<property key="ssoChangeTeamplateId" value="HLCDECHSSO"/>
	<property key="tuiChangeTeamplateId" value="HLCDECHTUI"/>

	<environment key="dev">
		<!--    <property key="wsprovider" value="mif" />-->
		<!--    <property key="targetmapping" value="maximo7.2.1"/>-->
		<property key="globalwsdlpath" value="https://170.225.28.205/MPWSNTestProxyWS/DocHandler?wsdl"/>
		<property key="globaservletpath_inc" value="https://170.225.28.205/HAPAGLLOYDINCTestWS/DocHandlerServlet"/>
		<property key="globaservletpath_chg" value="https://170.225.28.205/HAPAGLLOYDCHGTestWS/DocHandlerServlet"/>
		<property key="maximo_DB_url" value="Server=66.235.236.8:50005;Database=maxdb71;UID=maximo;PWD=Max1mo;CurrentSchema=maximo" />
		<property key="basewsURL" value="http://66.235.236.8/meaweb/wsdl/" />
		<property key="swdb_url" value="server=66.235.236.8;database=swdb_hapagdev;UID=sw;Pwd=sw;" />
		<property key="swdb_provider" value="MySql.Data.MySqlClient" />
		<property key="ldap.synceverytime" value="true"/>
		<property key="ldap.allownonmaximousers" value="true"/>
		<property key="ismcredentials.user" value="hl2tkbrg"/>
		<property key="ismcredentials.password" value="xK7AgFqJJQ"/>
	</environment>
	<environment key="qa">
		<property key="maximo_DB_url" value="Server=66.235.236.8:50005;Database=maxdb71;UID=maximo;PWD=Max1mo;CurrentSchema=maximo" />
		<property key="basewsURL" value="http://66.235.236.8/meaweb/wsdl/" />
		<property key="swdb_url" value="server=66.235.236.8;database=swdb_hapagqa;UID=sw;Pwd=sw;" />
		<property key="swdb_provider" value="MySql.Data.MySqlClient" />
	</environment>
	<environment key="prod">
		<property key="maximoutc" value="0"/>
		<property key="globalwsdlpath" value="https://170.225.28.205/MPWSNTestProxyWS/DocHandler?wsdl"/>
		<property key="globaservletpath_inc" value="https://170.225.28.205/HAPAGLLOYDINCTestWS/DocHandlerServlet"/>
		<property key="globaservletpath_chg" value="https://170.225.28.205/HAPAGLLOYDCHGTestWS/DocHandlerServlet"/>
		<property key="maximo_DB_url" value="Server=10.132.160.133:5101;Database=maximo;UID=maxsas;PWD=cD2g3nik;currentSchema=maximo;" />
		<property key="swdb_url" value="Data Source=localhost;Initial Catalog=swdb;User Id=swdb;password=sw;" />
		<property key="swdb_provider" value="System.Data.SQL" />
		<property key="ldapServer" value="adquery.hlag.com"/>
		<property key="ldapPortNumber" value="389"/>
		<property key="ldapBaseDn" value="dc=ww,dc=hl,dc=lan"/>
		<property key="targetmapping" value="ism"/>
		<property key="ldap.synceverytime" value="true"/>
		<property key="ldap.allownonmaximousers" value="true"/>
		<property key="basewsURL" value="C:\ServiceIT\config\mifwsdl\PROD\" />
		<property key="mifcredentials.user" value="dey99msy@ww.hl.lan"/>
		<property key="mifcredentials.password" value="maximo16"/>
		<property key="ismcredentials.user" value="hl2tkbrg"/>
		<property key="ismcredentials.password" value="xK7AgFqJJQ"/>
	</environment>

	<environment key="produat">
		<property key="maximoutc" value="0"/>
		<property key="globalwsdlpath" value="https://170.225.28.205/MPWSNTestProxyWS/DocHandler?wsdl"/>
		<property key="globaservletpath_inc" value="https://170.225.28.205/HAPAGLLOYDINCUATWS/DocHandlerServlet"/>
		<property key="globaservletpath_chg" value="https://170.225.28.205/HAPAGLLOYDCHGUATWS/DocHandlerServlet"/>
		<property key="maximo_DB_url" value="Server=10.132.160.132:5102;Database=maximo;UID=maxsas;PWD=xmax4sas;currentSchema=maximo;" />
		<property key="swdb_url" value="Data Source=localhost;Initial Catalog=swdb;User Id=sw;password=hapag123;" />
		<property key="swdb_provider" value="System.Data.SQL" />
		<property key="ldapServer" value="adquery.hlag.com"/>
		<property key="ldapPortNumber" value="389"/>
		<property key="ldapBaseDn" value="dc=ww,dc=hl,dc=lan"/>
		<property key="targetmapping" value="ism"/>
		<property key="ldap.synceverytime" value="true"/>
		<property key="ldap.allownonmaximousers" value="true"/>
		<property key="basewsURL" value="C:\ServiceIT\config\mifwsdl\UAT\" />
		<property key="mifcredentials.user" value="dey99msy@ww.hl.lan"/>
		<property key="mifcredentials.password" value="maximo16"/>
		<property key="ismcredentials.user" value="hl2tkbrg"/>
		<property key="ismcredentials.password" value="xK7AgFqJJQ"/>
	</environment>


</Properties>

=== lhrolim/softwrench/TestResults/testresults[1]/Out/client/kongsberg/properties.xml
<?xml version="1.0" encoding="utf-8" ?>
<Properties xmlns="http://www.example.org/Properties" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://www.example.org/Properties ../../Schema/Properties.xsd ">
  <property key="baseWSPrefix" value="SW"/>
  <property key="externalSystemName" value="SW" />
  <property key="wsprovider" value="mif" />
  <property key="basewsURL" value="http://66.235.236.83/meaweb/wsdl/" />
  <property key="maximo_DB_url" value="Data Source=192.168.2.21;Initial Catalog=KONGSUAT;User Id=MAXIMO;password=MAXIMO;" />
  <property key="maximo_DB_provider" value="System.Data.SQL"/>
  <property key="swdb_provider" value="System.Data.SQL"/>

  <property key="defaultOrgId" value="KOGT"/>
  <property key="defaultSiteId" value="SUPPORT24"/>
  <property key="email.smtp.host" value="mail.softwrenchsolutions.com"/>
  <!--property key="email.smtp.port" value="587"/-->
  <property key="email.stmp.enableSSL" value="true"/>

  <property key="sourcemapping" value="smartcloud7.5"/>
  <property key="targetmapping" value="smartcloud7.5"/>


  <environment key="dev">
    <property key="swdb_url" value="Data Source=192.168.2.21;Initial Catalog=SWDB_KONGSUAT;User Id=sw;password=softwrench;" />
  </environment>

  <environment key="qa">
    <property key="swdb_url" value="Data Source=192.168.2.21;Initial Catalog=SWDB_OTBQA;User Id=sw;password=softwrench;" />
  </environment>

</Properties>

=== lhrolim/softwrench/softWrench.sW4.Web/App_Data/client/scottsdale/properties.xml
<?xml version="1.0" encoding="utf-8" ?>
<Properties xmlns="http://www.example.org/Properties" ''
            xsi:schemaLocation="http://www.example.org/Properties ../../Schema/Properties.xsd ">

  <property key="baseWSPrefix" value="SW"/>
  <property key="externalSystemName" value="SW" />
  <property key="wsprovider" value="mif" />
  <property key="maximo_DB_provider" value="System.Data.SQL"/>
  <property key="swdb_provider" value="System.Data.SQL"/>
  <property key="defaultOrgId" value="EAGLENA"/>
  <property key="defaultSiteId" value="VQ"/>
  <property key="composition.mainbuttonstoshow" value="cancel"/>
  <property key="sourcemapping" value="maximo7.5"/>


  <environment key="dev">
    <property key="basewsURL" value="http://66.235.236.5/meaweb/wsdl/" />
    <property key="maximo_DB_url" value="Data Source=66.235.236.7;Initial Catalog=DEMO2MAX;User Id=MAXIMO;password=MAXIMO;" />
    <property key="swdb_url" value="Data Source=66.235.236.7;Initial Catalog=swdb_scottsdale;User Id=sw;password=softwrench;" />
  </environment>

  <environment key="qa">
    <property key="basewsURL" value="http://192.168.2.107/meaweb/wsdl/" />
    <property key="maximo_DB_url" value="Data Source=192.168.2.21;Initial Catalog=GRC75MAX;User Id=MAXIMO;password=MAXIMO;" />
    <property key="swdb_url" value="Data Source=192.168.2.21;Initial Catalog=SWDB;User Id=sw;password=sw@dm1n;" />
    <property key="ldapServer" value="192.168.2.11"/>
    <property key="ldapPortNumber" value="389"/>
    <property key="ldapBaseDn" value="ou=GROUPS,ou=MAXIMO,dc=sas,dc=local"/>
    <property key="mifcredentials.user" value="maxadmin"/>
    <property key="mifcredentials.password" value="M@xadm1n"/>
  </environment>
</Properties>
